baseurl = "https://ravuthz.github.io"
relativeurls = true
languageCode = 'en-us'
title = 'Ravuth Site'
theme = 'base16'

[taxonomies]
    categories = "categories"
    series = "series"
    tags = "tags"