baseurl = "https://ravuthz.github.io"
relativeurls = true
languageCode = 'en-us'
title = 'Ravuth Site'
theme = 'm10c'
paginate = 8

[taxonomies]
  categories = "categories"
  series = "series"
  tags = "tags"

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  debugbar = true
  author = "Ravuthz"
  avatar = "https://gravatar.com/avatar/3f9ea148ade811b13cc6adac470463d6?s=400&d=robohash&r=x"
  description = "Ravuthz blog"
  menu_item_separator = " - "
  favicon = "/favicon.ico"
    [[params.social]]
      icon = "github"
      name = "Github"
      url = "https://github.com/ravuthz"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"