name: github pages manual

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          cd ./public
          git config --global user.name = "Ravuthz"
          git config --global user.email = "ravuthz@gmail.com"
          git config --global init.defaultBranch = "gh-pages"
          git init
          git add .
          git commit -m "Deploy Githun Page at `date +'%Y-%m-%d %H:%M:%S'`"
          git push -f origin gh-pages
          exit(1)
          